name: Build and deploy
on:
  push:
    branches:
      - antora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: "get playbook"
        run: wget -O playbook.yaml https://raw.githubusercontent.com/eurobench/antora_playbook/main/playbook.yaml
      - name: Launch antora
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: playbook.yaml
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy Content
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          external_repository: eurobench/eurobench.github.io
          publish_branch: main
          publish_dir: ./build
          commit_message: ${{ github.event.head_commit.message }}